client:
  token: 
  display_name: Calidus-dev
database:
  driver: mysql
mail:
  driver: smtp
  driver_options:
    host: smtp-mail.outlook.com
    enable_ssl: true
modules:
  - name: event
    enabled: true
    role_format: "event_%"
    send_emails: true
    manage_roles: true
  - name: help
    enabled: true